name: BlazinSmelt
author: iiFlamiinBlaze
version: 1.0.0
description: An advanced auto inv and auto smelt plugin for PocketMine
main: iiFlamiinBlaze\BlazinSmelt\BlazinSmelt
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
softdepend: EconomyAPI